import sys
from colored import Fore, Back, Style
from primes import Primes

fm = Fore.magenta
fy = Fore.yellow
fg = Fore.green
sr = Style.reset

def print_title(title: str, info: str = ""):
    print(f"\n{fm}{title}{sr} {fg}{info}{sr}")
            
def print_value(name):
    obj = "p"
    var = eval(f"{obj}.{name}")
    print(name.ljust(30), f" = {fy}{var}{sr}")

def print_list(name):
    obj = "p"
    var = eval(f"{obj}.{name}")
    if len(var) > 10: var = str(var[:5]) + " ... " + str(var[-5:])
    print(name.ljust(30), f" = {fy}{var}{sr}")

def print_cli(p):
    print_title("Request")
    print_value("request.first")    
    print_value("request.last")
    print_value("request.count")
    print_value("request.interval")
    
    print_title("All", f"(all primes up to {p.request.last})")
    print_value("all.first.name")
    print_value("all.first.symbol")
    print_value("all.first.value")
    print_value("all.first.index")
    print_value("all.first.sufix")
    print_value("all.first.indexs")
    print_value("all.last.name")
    print_value("all.last.symbol")
    print_value("all.last.value")
    print_value("all.last.index")
    print_value("all.last.sufix")
    print_value("all.last.indexs")
    print_value("all.count")
    print_value("all.interval")
    print_list("all.list")
    
    print_title("Range", f"(primes in requested range)")
    print_value("range.result")
    print_value("range.count")
    print_value("range.interval")
    print_list("range.list")
    print_value("range.first.name")
    print_value("range.first.symbol")
    print_value("range.first.value")
    print_value("range.first.index")
    print_value("range.first.sufix")
    print_value("range.first.indexs")
    print_value("range.last.name")
    print_value("range.last.symbol")
    print_value("range.last.value")
    print_value("range.last.index")
    print_value("range.last.sufix")
    print_value("range.last.indexs")
    
    print_title("Gaps")
    print_value("gaps.max.name")
    print_value("gaps.max.symbol")
    print_value("gaps.max.value")
    print_value("gaps.max.count")
    print_list("gaps.max.list")
    print_value("gaps.min.name")
    print_value("gaps.min.symbol")
    print_value("gaps.min.value")
    print_value("gaps.min.count")
    print_list("gaps.min.list")
    print_value("gaps.com.name")
    print_value("gaps.com.symbol")
    print_value("gaps.com.value")
    print_value("gaps.com.count")
    print_list("gaps.com.list")
    print_value("gaps.name")
    print_value("gaps.kinds")
    print_list("gaps.list")
    
    print_title("Stats")
    print_value("pcent.name")
    print_value("pcent.symbol")
    print_value("pcent.value")
    print_value("sum.name")
    print_value("sum.symbol")
    print_value("sum.value")
    print_value("mean.name")
    print_value("mean.symbol")
    print_value("mean.value")
    print_value("median.name")
    print_value("median.symbol")
    print_value("median.value")
    print_value("pstdev.name")
    print_value("pstdev.symbol")
    print_value("pstdev.value")
    print_value("pvariance.name")
    print_value("pvariance.symbol")
    print_value("pvariance.value")
    if p.range.count > 1:
        print_value("stdev.name")
        print_value("stdev.symbol")
        print_value("stdev.value")
        print_value("variance.name")
        print_value("variance.symbol")
        print_value("variance.value")
        print_value("q1.name")
        print_value("q1.symbol")
        print_value("q1.value")
        print_value("q3.name")
        print_value("q3.symbol")
        print_value("q3.value")
        print_value("qi.name")
        print_value("qi.symbol")
        print_value("qi.value")
    
    print_title("Curiosities")
    print_value("thabits.name")
    print_value("thabits.form")
    print_value("thabits.count")
    print_value("thabits.first")
    print_value("thabits.last")
    print_list("thabits.list")
    print_value("mersennes.name")
    print_value("mersennes.form")
    print_value("mersennes.count")
    print_value("mersennes.first")
    print_value("mersennes.last")
    print_list("mersennes.list")
    print_value("fermats.name")
    print_value("fermats.form")
    print_value("fermats.count")
    print_value("fermats.first")
    print_value("fermats.last")
    print_list("fermats.list")
    print_value("wagstaffs.name")
    print_value("wagstaffs.form")
    print_value("wagstaffs.count")
    print_value("wagstaffs.first")
    print_value("wagstaffs.last")
    print_list("wagstaffs.list")


    print_title("Time")
    print_value("time.sieve.name")
    print_value("time.sieve.start")
    print_value("time.sieve.stop")
    print_value("time.sieve.diff")
    print_value("time.sieve.value")
    print_value("time.gaps.name")
    print_value("time.gaps.start")
    print_value("time.gaps.stop")
    print_value("time.gaps.diff")
    print_value("time.gaps.value")
    print_value("time.basics.name")
    print_value("time.basics.start")
    print_value("time.basics.stop")
    print_value("time.basics.diff")
    print_value("time.basics.value")
    print_value("time.stats.name")
    print_value("time.stats.start")
    print_value("time.stats.stop")
    print_value("time.stats.diff")
    print_value("time.stats.value")
    print_value("time.weird.name")
    print_value("time.weird.start")
    print_value("time.weird.stop")
    print_value("time.weird.diff")
    print_value("time.weird.value")
    print_value("time.total.name")
    print_value("time.total.start")
    print_value("time.total.stop")
    print_value("time.total.diff")
    print_value("time.total.value")
    print_value("time.unit")

if len(sys.argv) == 3:
    p = Primes(sys.argv[1], sys.argv[2])
else:
    p = Primes(1, sys.argv[1])
if not p.error:
    print_cli(p)
    sys.exit(0)
else:
    sys.exit(1)
